apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: europe-west4-docker.pkg.dev/qwiklabs-gcp-04-fade99ab4f58/my-repository/hello-cloudbuild:v2.0
        ports:
        - containerPort: 8080
